[project]
name = "story_writer_flow"
version = "0.1.0"
description = "story_writer_flow using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=1.15.18,<2.0.0"
]

[project.scripts]
kickoff = "story_writer_flow.main:kickoff"
run_crew = "story_writer_flow.main:kickoff"
plot = "story_writer_flow.main:plot"
run_with_trigger = "story_writer_flow.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "flow"
project_id = "35c1215c-d14d-4e0f-851d-f6227bee69c2"
